### ISSUE TITLE
UDP ExID

### ISSUE THREAD

**Issue by tireddy2** [boucadair/udp-ipfix#1]
I don't see how UDP Experimental ID (ExIDs) will be conveyed ?

**Comment by boucadair** [comment]
Yes. This is one of the points I wanted to cover in the next revision. 

This will require a new IE. What I had in mind is when 127 is set in the udpOptions, the new IE will also be included with the oserved ExIDs

```
+----------+----------+----------+----------+   +----------+----------+
|      UDP ExID#1        |   UDP ExID#2           | ... .|   UDP ExID#i           | 
+----------+----------+----------+----------+   +----------+----------+
```
